spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/rest2023_dev?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
  jpa:
    hibernate:
      ddl-auto: create